BOT_TOKEN: 
  - NzY0NDIyMDM4NTc1OTA2ODU3.GzBcZX.vLsrXJ6diWZxddgCiUKd5niNNxV0sJPpFGSfMQ
CHANNEL_ID: 
  - 852747615552405539
MODE: quote
REPLY:
SIMSIMI_LANG: en
DELAY: 5
DEL_AFTER: 
REPOST_LAST_CHAT: 100